Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# Bag of words

it will count the number of occurence of words existing in a text(also called as Document)

It takes care of text of any length even if they are matching with other text length

In [1]:
import numpy as np
import pandas as pd

In [2]:
# create a datframe with text values and assigned output
df = pd.DataFrame({"text":["people watch movies watch",
                         "ravi watch movies",
                         "people write comment",
                          "ravi write comment ",
                           "zebra yelling"],"output":[1,1,0,0,1]})

df

text  output
0  people watch movies watch       1
1          ravi watch movies       1
2       people write comment       0
3        ravi write comment        0
4              zebra yelling       1

In [3]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [4]:
# generating bag of words from the text

bow = cv.fit_transform(df['text'])

In [5]:
# printing vocabulary from the corpus, numerical values are assigned to each words in their  alphabetical orders
# word "comment" , since it starts with "c" and its first in alphabet list among all other words, it has numerical value = 0
# word  "people" starts with "p" so it has numerical value = 1
# word "zebra" starts with "z" which is last in the word list hence it has the last value = 7

print(cv.vocabulary_)

{'people': 2, 'watch': 4, 'movies': 1, 'ravi': 3, 'write': 5, 'comment': 0, 'zebra': 7, 'yelling': 6}


In [6]:
# printing bag of words

print(bow)

  (0, 2)	1
  (0, 4)	2
  (0, 1)	1
  (1, 4)	1
  (1, 1)	1
  (1, 3)	1
  (2, 2)	1
  (2, 5)	1
  (2, 0)	1
  (3, 3)	1
  (3, 5)	1
  (3, 0)	1
  (4, 7)	1
  (4, 6)	1


first value in the tuple is row number of the text  and second value is the vocabulary number generated for each words

ie (0,4) 2 = row number "0" identify its first text, "4" identifies that second word in text1 = "watch" which has been assigned 4 in the vocabulary list while "2" signifies the count of word "watch" appears twice in the text1

In [7]:
# converting bag of words to array and printing it


print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())


[[0 1 1 0 2 0 0 0]]
[[0 1 0 1 1 0 0 0]]
[[1 0 1 0 0 1 0 0]]
[[1 0 0 1 0 1 0 0]]


text 1 = "people watch movies"
bag of words for text1 = [0 1 1 0 2 0 0 0]

"comment" which is at 0th position in vocabulary and it does not exists in the text1  so 1st value in array = 0

"movies" is the at 1st position in the vocabulary and it exists in the text1 so 2nd value in array = 1

"people" is the at 2nd position in the vocabulary and it exists in the text1 so 3rd value in array = 1

"ravi" is the at 3rd position in the vocabulary and it does not exists in the text1 so 4th value in array = 0

"watch" is the at 4th position in the vocabulary and it exists in the text1 twice so 5th value in array = 2

"write" is the at 5th position in the vocabulary and it does not exists in the
text1 so 6th value in array = 0

"yelling" is the at 6th position in the vocabulary and it does not exists in the text1 so 7th value in array = 0

"zebra" is the at 7th position in the vocabulary and it does not exists in the text1 so 8th value in array = 0

In [8]:
# transforming new text

print(cv.transform(['People watch movies and Radha write its summary in india context']))

  (0, 1)	1
  (0, 2)	1
  (0, 4)	1
  (0, 5)	1


In [9]:
# Transforming new document text

# it will check if the vocabulary from the corpus exists in the the provided text

# "comment" which is at 0th position in vocabulary does not exists in the text so 1st value in array = 0
# "movies" is the at 1st position in the vocabulary and it exists in the text so 2nd value in array = 1
# "people" is the at 2nd position in the vocabulary and it exists in the text so 3rd value in array = 1
# "ravi" is the at 3rd position in the vocabulary and it does not exists in the text so 4th value in array = 0
# "watch" is the at 4th position in the vocabulary and it exists in the text so 5th value in array = 1
# "write" is the at 5th position in the vocabulary and it exists in the text so 6th value in array = 1
# "yelling" is the at 6th position in the vocabulary and it does not exists in the text1 so 7th value in array = 0
# "zebra" is the at 7th position in the vocabulary and it does not exists in the text1 so 8th value in array = 0

cv.transform(['People watch movies and Radha write its summary in india context']).toarray()

array([[0, 1, 1, 0, 1, 1, 0, 0]])

In [10]:
# Assigning X with bag of words
# y = output value from dataframes
X = bow.toarray()
y = df['output']

In [11]:
X

array([[0, 1, 1, 0, 2, 0, 0, 0],
       [0, 1, 0, 1, 1, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0],
       [1, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 1]])

In [12]:
y

0    1
1    1
2    0
3    0
4    1
Name: output, dtype: int64

#  N-grams

It is bag of words

In [13]:
# create a datframe with text values and assigned output

df = pd.DataFrame({"text":["people watch movies watch",
                         "ravi watch movies",
                         "people write comment",
                          "ravi write comment",
                           "zebra yelling"],"output":[1,1,0,0,1]})

df

text  output
0  people watch movies watch       1
1          ravi watch movies       1
2       people write comment       0
3         ravi write comment       0
4              zebra yelling       1

In [14]:
# BI grams with ngram_range = (2,2 )
# It will use 2 consecutive words from the text and will be treated as 1 unique word for the corpus

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [15]:
bow = cv.fit_transform(df['text'])

In [16]:
print(cv.vocabulary_)

{'people watch': 1, 'watch movies': 5, 'movies watch': 0, 'ravi watch': 3, 'people write': 2, 'write comment': 6, 'ravi write': 4, 'zebra yelling': 7}


In [17]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())
print(bow[4].toarray())

[[1 1 0 0 0 1 0 0]]
[[0 0 0 1 0 1 0 0]]
[[0 0 1 0 0 0 1 0]]
[[0 0 0 0 1 0 1 0]]
[[0 0 0 0 0 0 0 1]]


In [18]:
# Ti gram
# BI grams
# It will use 3 consecutive words from the text and it will be treated as 1 unique word(vocabulary) for the corpus
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [19]:
bow = cv.fit_transform(df['text'])

In [20]:
print(cv.vocabulary_)

{'people watch movies': 0, 'watch movies watch': 4, 'ravi watch movies': 2, 'people write comment': 1, 'ravi write comment': 3}


Since we have given ngram = (3,3) and last text "zebra yelling" only had 2 words so it got ingored from the vocabulary list

In [21]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())
print(bow[4].toarray())


[[1 0 0 0 1]]
[[0 0 1 0 0]]
[[0 1 0 0 0]]
[[0 0 0 1 0]]
[[0 0 0 0 0]]


# TF-IDF (Term frequency- Inverse document frequency)

In [22]:
# create a datframe with text values and assigned output

df = pd.DataFrame({"text":["people watch movies watch",
                         "ravi watch movies",
                         "people write comment",
                          "ravi write comment",
                           "zebra yelling"],"output":[1,1,0,0,1]})

df

text  output
0  people watch movies watch       1
1          ravi watch movies       1
2       people write comment       0
3         ravi write comment       0
4              zebra yelling       1

In [23]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [24]:
tfid.fit_transform(df['text']).toarray()

array([[0.        , 0.40824829, 0.40824829, 0.        , 0.81649658,
        0.        , 0.        , 0.        ],
       [0.        , 0.57735027, 0.        , 0.57735027, 0.57735027,
        0.        , 0.        , 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.        ,
        0.57735027, 0.        , 0.        ],
       [0.57735027, 0.        , 0.        , 0.57735027, 0.        ,
        0.57735027, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.70710678, 0.70710678]])

In [25]:
print(tfid.idf_)

[1.69314718 1.69314718 1.69314718 1.69314718 1.69314718 1.69314718
 2.09861229 2.09861229]
